


# Number=[3, 5, 7, 34, 2, 89, 2, 5]
# print(max(Number))





# numbers = [1, 2, 3, 4, 5]
# i=0
# sum=0
# while i<len(numbers):
#     sum=sum+numbers[i]
#     i+=1
# print(sum)




# unorder_list = [6, 8, 4, 3, 9, 56, 0, 34, 7, 15]
# unorder_list.sort()
# print(unorder_list)





# reverse_list = ["Z", "A", "A", "B", "E", "M", "A", "R", "D"]
# reverse_list.reverse()
# print(reverse_list)


# list = [8, 6, 4, 8, 4, 50, 2, 7]
# print(min(list))


# def sum():
#     print(12+13)
# sum()



# def welcome():
#     print("Welcome to function")
# welcome()



# def isEven():
#     if(12%2==0):
#         print("Even Number")
#     else:
#         print("Old Number")
# isEven()


# def greet(names):
#     for name in names:
#         print("Welcome", name)
# greet("Rinki", "Vishal", "Kartik", "Bijender")


def info(name,age=):
    print(name + " is " + age + " years old")
    info("Sonu","10")
    info("Sana", "17")
    info("Umesh", "18")




